### ISSUE TITLE
Ticket #1 - Ajoutez un système de réservation d’ouvrages (par le client)

### ISSUE THREAD

**Issue by Vifier-Lockla** [YoannR09/Projet_10_OC#1]
Bonjour,

Nous souhaiterions mettre en place un système de réservation de livres pour les usagers.

Le principe est le suivant :

L’usager peut vouloir emprunter un livre dont aucun exemplaire n’est actuellement disponible (ils sont tous en cours de prêt). Il a donc la possibilité de réserver l’ouvrage. Le premier à avoir réservé aura la priorité de la réservation dès le retour d’un exemplaire. Chaque ouvrage (titre, pas exemplaire) aura donc une liste d’attente de réservation. Dès qu’un exemplaire est de retour à la bibliothèque, un mail est envoyé au premier usager de la liste et il dispose de 48h pour venir le chercher. Passé ce délai, sa réservation est annulée et un mail est envoyé au suivant, etc. 

### Règles de gestions : 
- Tous les types d’ouvrages peuvent être réservés.
- La liste de réservation ne peut comporter qu’un maximum de personnes correspondant à 2x le nombre d’exemplaires de l’ouvrage.
- Il n’est pas possible pour un usager de réserver un ouvrage qu’il a déjà en cours d’emprunt
- Quand un usager emprunte le livre réservé ou si le délai de 48h après la notification est dépassé, sa réservation est supprimée de la liste et le processus recommence pour l’usage suivant dans la liste
    - Sur l’application web :
        - Lors de la recherche d’ouvrage, pour ceux indisponibles, il doit y avoir la date de retour prévue la plus proche et le nombre de personnes ayant réservé l’ouvrage. Si la liste d’attente de l’ouvrage n’est pas complète, il doit pouvoir demander une réservation. Il sera alors ajouté à la liste d’attente
        - L’usager doit pouvoir avoir une liste des réservations qu’il a en cours avec pour chaque ouvrage la prochaine date de retour prévue et sa position dans la liste d’attente
        - L’usager doit pouvoir annuler une réservation

Avertissez-nous avant de livrer cette évolution afin que nous nous organisions. De plus cette demande n’est pas urgente et il est possible que nous vous demandions d’autres évolutions à embarquer en même temps dans la nouvelle version du système.

**Comment by YoannR09** [comment]
##  Modifications apportés à l'application
          
          
### Etape 1 : "Modifcation UML de la nouvelle fonctionnalité"

   - Modifications et ajouts de plusieurs use case sur la partie UML.
   
   <img width="295" alt="uml_1" src="https://user-images.githubusercontent.com/38251071/68068976-02108880-fd5b-11e9-8ad3-e2fbe9e5edf2.png">
           
   
<img width="560" alt="uml_2" src="https://user-images.githubusercontent.com/38251071/68068990-15bbef00-fd5b-11e9-9e7e-c71b6c7035ca.png">

           
<img width="578" alt="uml_3" src="https://user-images.githubusercontent.com/38251071/68068993-1d7b9380-fd5b-11e9-83df-a1e039ca96ac.png">

   - Ajout des fiches déscriptives et diagramme d'activité des nouveaux use case.
   
<img width="555" alt="uml_4" src="https://user-images.githubusercontent.com/38251071/68068995-266c6500-fd5b-11e9-935c-c9e55b25cc38.png">

<img width="485" alt="uml_5" src="https://user-images.githubusercontent.com/38251071/68068997-29675580-fd5b-11e9-9d30-a440132a0b63.png">

   - Ajout de plusieurs wireframes.

<img width="510" alt="wireframe_1" src="https://user-images.githubusercontent.com/38251071/68069000-3c7a2580-fd5b-11e9-9fc3-5111a648664a.png">
<img width="548" alt="wireframe_2" src="https://user-images.githubusercontent.com/38251071/68069001-3c7a2580-fd5b-11e9-8e0d-777474687fa9.png">
<img width="810" alt="wireframe_3" src="https://user-images.githubusercontent.com/38251071/68069002-3c7a2580-fd5b-11e9-9d0f-f54681b6e9a4.png">
<img width="618" alt="wireframe_4" src="https://user-images.githubusercontent.com/38251071/68069003-3c7a2580-fd5b-11e9-9570-84b48d09084e.png">
<img width="812" alt="wireframe_5" src="https://user-images.githubusercontent.com/38251071/68069004-3d12bc00-fd5b-11e9-87d4-ab0f0186a0ab.png">

    
### Etape 2 : "Mise en place de la nouvelle table."

#### 1.
    - Ajout d'une table "reservation" dans la base de données.
    
![table](https://user-images.githubusercontent.com/38251071/68069013-48fe7e00-fd5b-11e9-9f05-89b7cc75d396.png)

   
       - abonne_id pour définir à qui est la réservation.
       - livre_id pour définir sur quel livre est la réservation.
       - bibliotheque_id pour définir dans quel bibliotheque la réservation est attendu.
       - livre_id pour définir un exemplaire une fois que celui-ci est disponible.
   
 #### 2.
 
    - Création du microservice de cette table.   
    - Mise en place des tests du microservice.
    - Création du controller qui récupère les données du nouveau microservice.
    
 #### 3.
 
    - Ajout d'une valeur "sous-reserve" dans la table livre_unique.
    celle-ci permet pendant la vérification toute les heures de savoir
    si la réservation a été retiré pour un prêt ou non.
    - Modification des objets LivreUnique pour mettre cette valeur en place.
    
 ### Etape 3 : "Modification de la partie web."
 
    - Modification de la barre de navigation pour les employés et abonnés.
    - Ajout d'une page jsp pour consulter les réservations d'un abonné.
    
<img width="872" alt="image_resa_employe" src="https://user-images.githubusercontent.com/38251071/68069018-53207c80-fd5b-11e9-892b-60cef673bfe9.png">

   
    - Ajout d'une page jsp pour consulter ses réservations en cours.
    
  
<img width="839" alt="image_resa_abonne" src="https://user-images.githubusercontent.com/38251071/68069022-5ca9e480-fd5b-11e9-8f76-2fc6da0b08cd.png">

       
       
    - Modification d'une page jsp pour ajouter un bouton reserver.
    
   
<img width="779" alt="image_detail_livre" src="https://user-images.githubusercontent.com/38251071/68069028-63385c00-fd5b-11e9-9f2a-86c6daacb5dc.png">

   
    
    - Ajout d'une page jsp pour créer une réservation.
    
   
<img width="899" alt="image_edit_resa" src="https://user-images.githubusercontent.com/38251071/68069030-6895a680-fd5b-11e9-84c8-e9b74382e98d.png">

   
 ### Etape 3 : "Intégration de la nouvelle fonctionnalité"

    - Ajout d'un bean de l'objet réservation.
    - Ajout d'une classe action pour la partie réservation.
    - Ajout d'une méthode dans la classe GestionLivreAction pour rajouter la possiblité
    de réserver pendant la consultation des détails d'un livre.
    - Création d'une classe qui gère l'envoie des mails une fois qu'un exemplaire a 
    été restitué à la bibliothèque.
    - Création d'une méthode dans la classe qui gère les mails, cette classe lance un timer de
    deux jours après l'envoie d'un mail de réservation. Si la personne ne récupére pas son livre 
    dans les deux jours la réservation est supprimée.
    - Création d'une méthode dans la classe qui gère les mails, cette méthode consulte toutes
    les heures si la réservation est toujours existante.
