### ISSUE TITLE
Ticket #2 - Corrigez un bug dans la gestion des prolongations de prêt (par le client)

### ISSUE THREAD

**Issue by Vifier-Lockla** [YoannR09/Projet_10_OC#2]
Nous avons découvert un bug de la gestion des prolongations de prêt. En effet, un usager peut prolonger un prêt après la date butoir. Il ne doit pas être possible pour l’usager de prolonger un prêt si la date de fin de prêt est dépassée.

La correction de cette anomalie est urgente car elle nous pose de gros problèmes de gestion. Actuellement beaucoup trop de personnes attendent le mail de rappel pour prolonger leur prêt. Cela entraîne la plainte de certains usagers à qui nous avions communiqué une date de retour et qui se déplacent en bibliothèque pour rien car le prêt a été prolongé a posteriori.

Je vous demande de livrer une nouvelle version de l’application au plus vite afin de corriger ce bug mais sans inclure nos autres demandes en cours. Nous souhaiterions pouvoir mettre en production rapidement sans avoir à faire de recette sur les autres évolutions demandées.

**Comment by YoannR09** [comment]
##  Ticket n°2
   
#### L'abonné ne peut pas prolonger son prêt après le delai dépassé. :
   
   - Ajout d'un boolean expire pour l'objet prêt.
   - Compare la date actuel et celle de resitution du prêt.
   - En fonction du résultat l'objet expire est vrai ou faux.
  
    ![compareDate](https://user-images.githubusercontent.com/38251071/67418050-5fbe0b80-f5ca-11e9-8a85-6b8d12d82ab1.png)

   
   - Si expire est true on affiche un bouton disable.
   - Si expire est false on affiche le bouton qui permet de prolonger le prêt en cours
  
![jspExpire](https://user-images.githubusercontent.com/38251071/67418083-706e8180-f5ca-11e9-96c1-e34c51aa4979.png)

**Comment by YoannR09** [comment]
<img width="563" alt="back_end_prolongation" src="https://user-images.githubusercontent.com/38251071/74265163-50daa080-4d02-11ea-830a-8fd48defff8d.png">
