### ISSUE TITLE
Ticket #3 - Mettez en place une stratégie de tests (par le Tech Lead)

### ISSUE THREAD

**Issue by Vifier-Lockla** [YoannR09/Projet_10_OC#4]
Après un code review de la V1 je me suis rendu compte que des tests unitaires n’ont pas été implémentés, on est donc hors des process de qualité sur cette release....
Pour la release qui est en cours de développement, merci de mettre en place une stratégie de tests pour le code API :
- Des tests unitaires pour valider les parties métiers du code API (l’utilisation de JUnit devrait faire l’affaire, à vous de voir s’il y a besoin de faire des mocks ou non)

- Des tests d’intégration de l’API via un outil de tests d’API (ex : Postman, Soap-UI)

Pour les tests de l’application web et du batch, on verra dans un second temps. Je vous tiendrai au courant…

**Comment by YoannR09** [comment]
##  Modifications apportés à l'application pour les tests.
   
### Test unitaires :


   - Ajouts des méthodes getDao() et getLogger() pour pouvoir créer un fake.
   
  
<img width="362" alt="methode" src="https://user-images.githubusercontent.com/38251071/68069089-f5406480-fd5b-11e9-8487-11f090a7a57c.png">

   
   - Mise en place des mocks et stubs.
   
 
<img width="279" alt="mock_stub" src="https://user-images.githubusercontent.com/38251071/68069092-fc677280-fd5b-11e9-9f81-08305ae7768c.png">

   
   - Création du fake dans la classe de test avec les mocks.
   
  
<img width="363" alt="fake" src="https://user-images.githubusercontent.com/38251071/68069093-025d5380-fd5c-11e9-960c-3fe01dce7dc1.png">

   
   - Test des méthodes et vérification des exceptions.
   
   
<img width="503" alt="test" src="https://user-images.githubusercontent.com/38251071/68069094-07220780-fd5c-11e9-8e15-50abaf53fd9e.png">

   
   
   
### Test d'intégrations : 
 
   - Création d'une collection sur Postman : https://www.getpostman.com/collections/089e535339b4f4936f3e
   
    
<img width="366" alt="collection" src="https://user-images.githubusercontent.com/38251071/68069099-0ee1ac00-fd5c-11e9-882f-e9df88fd77bf.png">

  
   - Intégration des tests pour les requetes de la collection.
   
      
<img width="714" alt="collection_test" src="https://user-images.githubusercontent.com/38251071/68069102-143ef680-fd5c-11e9-8649-44d3c8b0733b.png">

   
   - Création du fichier de la collection en json pour pouvoir
   lancer le test via Travis CI.
   
      
<img width="663" alt="collection_json" src="https://user-images.githubusercontent.com/38251071/68069103-186b1400-fd5c-11e9-9575-bc638d6a6aa8.png">

   
   - Installation de node.js en local pour vérifier les test d'intégrations.
   - Installation de newman pour lancer les tests de la collection.
   
   - Vérification des tests via newman :
   
<img width="388" alt="newman" src="https://user-images.githubusercontent.com/38251071/68069223-a98eba80-fd5d-11e9-8503-dae0f823106e.png">

   
   - Ajout d'un fichier travis ci qui lance la collection de test postman avec newman.
   (Les microservices ne sont pas encore mis en ligne, travis ci ne peut donc
   pas récupérer les données avec les requetes.)
   
   
<img width="495" alt="travis" src="https://user-images.githubusercontent.com/38251071/68069226-b0b5c880-fd5d-11e9-8016-ce690ee28ef4.png">
